import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white" className="bg-neutral-950 text-neutral-100">{children}      <a href="/" aria-label="Home" data-planet-home
         style={{position:'fixed', right:'16px', bottom:'16px', zIndex:50,
                 width:'48px', height:'48px', display:'grid', placeItems:'center',
                 borderRadius:'9999px', border:'1px solid rgba(255,255,255,0.2)',
                 background:'rgba(0,0,0,0.4)', backdropFilter:'blur(6px)'}}
         className="hover:scale-105 transition">
        <span style={{fontSize:'22px', lineHeight:1}}>🪐</span>
      </a></body>
    </html>
  )
}
